import json

def verifier_instr(entry):
    task = entry['task']
    entry_input = json.loads(entry['input'])
    instr_map = {
        "answerability_prediction": "The model needs to analyze the question related to the product in the image based on its supporting document. Here is the input: ['question': '{}', 'document': '{}']. You need to determine how the product image will contribute to identifying the question's answerability. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D.".format(entry_input['question'], json.dumps(entry_input['document'])),
        "binary-question_answering": "The model needs to answer the yes-no question related to the product in the image based on its supporting document. Here is the input: ['question': '{}', 'document': '{}']. You need to determine how the product image will contribute to question answering. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D.".format(entry_input['question'], json.dumps(entry_input['document'])),
        "click-through_predction": "The model needs to predict if the user would like to buy the candidate product given the user's purchase history. Here is the input: ['purchase hisroty': '{}', 'candidate product': '{}']. You need to determine how the product image will contribute to question answering. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D.".format(', '.join(['Product ' + str(idx+1) + ': ' + item['text'] for idx, item in enumerate(entry_input['purchase history'])]), entry_input['candidate']['text']),
        "sequential_recommendation": "The model needs to estimate the user's purchase intent based on the user's purchase history, and predict the next product that the user is most likely to purchase. Here is the input: [{}]. You need to determine how the product images will contribute to estimating the user's intent. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D.".format(', '.join(['product ' + str(idx+1) + ': ' + item['text'] for idx, item in enumerate(entry_input['purchase history'])])),
        "multiclass_product_classification": f"The model needs to predict the relevance between the query and product in the image by analyzing the user's query and product title. Here is the input: ['query': '{entry_input['query']}', 'product title': '{entry_input['product title']}']. You need to determine how the product image will contribute to predicting the relevance. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option A, B, C, or D.",
        "production_substitute_identification": f"The model needs to identify if a product is somewhat relevant to the query but fails to fulfill some aspects of the query but the product can be used as a functional substitute given a user's query, product title and product image. Here is the input: ['query': '{entry_input['query']}', 'product title': '{entry_input['product title']}']. You need to determine how the product image will contribute to identifying the query-product relevance. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D.",
        "product_relation_prediction": f"The model needs to predict the relation of the two products given the titles and images of them. Here is the input: ['product 1 title': '{entry_input['product1 title']}', 'product 2 title': '{entry_input['product2 title']}']. You need to determine how the product images will contribute to predicting the products relationship. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D.",
        "sentiment_analysis": f"The model needs to identify the user's rating to the product based the user's review text and image. Here is the input: ['review': '{entry_input['user review']}']. You need to determine how the review image will contribute to identifying the user's rating. Here are the options: ['A: helpful', 'B: potential helpful', 'C: potential harmful', 'D: harmful']. ONLY answer option letters: A, B, C, or D."
    }

    return instr_map.get(task, "Invalid task")